name: Go

on:
  push:
    branches: [v2.dev]
  pull_request:
    branches: [v2.dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
        options: >-
          --health-cmd nodetool statusgossip
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -tags=cassandra ./...
